### ISSUE TITLE
Question: Using docker secrets with swarm launcher?

### ISSUE THREAD

**Issue by shrikeh** [ix-ai/swarm-launcher#31]
I was wondering given that the underlying container is run via docker-compose and not swarm, is it possible that I give the launcher a secret and it interprets it for the underlying container? For example, I'm looking at the `gluetun` vpn client and it owuld be great if the environment variables came from a secret (indirectly, with the swarm launcher interpreting it as env vars)

**Comment by tlex** [comment]
This is an interesting question.

This feature doesn't exist as such, but there might be a way to make it work.

To check that I understand the use case better, I'll try structuring it a bit:

* you store a USER and a PASS as docker swarm secrets
* you start swarm-launcher with those secrets exposed inside (let's call them `/run/secrets/user' and `/run/secrets/pass')
* you start `gluetun:latest` with a volume mount `/run/secrets/user:/run/secrets/user` and another one `/run/secrets/user:/run/secrets/pass`

Does that cover it?

If yes, it's possible to use the environment variable `LAUNCH_VOLUMES` which, in our example, would be set to:
```yml
services:
secrets:
  user:
    external: true # assuming that you manage storing the secrets outside of the stack file
  pass:
    external: true
  swarm-launcher-gluetun:
    secrets:
      - user
      - pass
    image: ghcr.io/ix-ai/swarm-launcher:latest
    [...]
    environment:
      LAUNCH_IMAGE: 'qmcgaw/gluetun:latest' # Note: I don't know gluetun, I chose the first image from google
      LAUNCH_ENVIRONMENTS: 'OPENVPN_PASSWORD_SECRETFILE=/run/secrets/pass OPENVPN_USER_SECRETFILE=/run/secrets/user'
      LAUNCH_VOLUMES: '/run/secrets/pass:/run/secrets/pass:ro /run/secrets/user:/run/secrets/user:ro' # setting to `ro` since no write access is needed
      [...]
```

Hope this helps
