### ISSUE TITLE
Automatically restart unhealthy container?

### ISSUE THREAD

**Issue by sxiii** [ix-ai/swarm-launcher#7]
Hi!

Usually, when I run containers in swarm, I add something like that for example (as for chromium)

```
HEALTHCHECK --interval=1m --timeout=3s CMD curl -f http://localhost:3000 || exit 1
```

But when I run containers via swarm-launcher, the health check does not work. After the child container starts being unhealthy it's not automatically restarted. As I can understand it's because the containers are started by the swarm-launcher while docker normally does not have the healthcheck functionality (only in swarm directly deployed services).

Is there any option for making HEALTHCHECK work in while launching via swarm-launcher?

Thanks.

**Comment by sxiii** [comment]
I'm trying to add this as a replacement:
```
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      timeout: 5s
      retries: 5
```

So the question is here... Would the swarm-launcher have an access to check localhost's 3000 port? And in the case it works... Should I remove check from my main docker container?

**Comment by sxiii** [comment]
Also trying now approach with overlay networks:
```
    networks:
      - myoverlay
    environment:
      LAUNCH_IMAGE: dvv
      LAUNCH_DEVICES: '/dev/net/tun:/dev/net/tun'
      LAUNCH_VOLUMES: '/var/run/docker.sock:/var/run/docker.sock:rw'
      LAUNCH_NETWORKS: 'myoverlay'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      timeout: 5s
      retries: 5
networks:
  myoverlay:
    driver: "overlay"
```

Might this work?

**Comment by tlex** [comment]
In the last example, this can only work if you add the prefix of the stack to `LAUNCH_NETWORKS: 'myoverlay'`. It means, if the stack is called `foo`, then you need to modify the line to read `LAUNCH_NETWORKS: 'foo_myoverlay'`.

I haven't looked yet into the healthcheck - it's an interesting approach to mark the swarm-launcher as healthy once the started container has a port open. I'll give it a try.

**Comment by tlex** [comment]
Give it a try with [v0.4.0](https://github.com/ix-ai/swarm-launcher/releases/tag/v0.4.0), since `curl` is now available.

**Comment by sxiii** [comment]
Hi!

Thanks for your answers and improvements. Here are my updates:

I am trying to get it to work, by creating a network called myoverlay first:

```
sudo docker network create -d overlay --attachable myoverlay
```

Then I am using the following `stack.yml`:

```                                              
version: "3.7"

services:
  runner-launcher:
    deploy:
      mode: global
      restart_policy:
        delay: 5s
    image: ixdotai/swarm-launcher:latest
    networks:
      - myoverlay
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
    environment:
      LAUNCH_IMAGE: dvv
      LAUNCH_PROJECT_NAME: 'DVVP'
      LAUNCH_SERVICE_NAME: 'DVVS'
      LAUNCH_PRIVILEGED: 'true'
      LAUNCH_EXT_NETWORKS: 'myoverlay_myoverlay'
      LAUNCH_ENVIRONMENTS: 'access_token=some_token'
      LAUNCH_DEVICES: '/dev/net/tun:/dev/net/tun'
      LAUNCH_VOLUMES: '/var/run/docker.sock:/var/run/docker.sock:rw'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      timeout: 5s
      retries: 15
      start_period: 30s
networks:
  myoverlay:
    driver: 'overlay'
    attachable: true
```
But here's what I see in the result all the time, tried with different settings already:
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                            PORTS               NAMES
3ca7fb1f4564        dvv                             "/run.sh"                2 minutes ago       Up 2 minutes (healthy)                                dvvp_DVVS_1
7b42ceceb25c        ixdotai/swarm-launcher:latest   "/bin/sh -c /entrypo…"   2 minutes ago       Up 2 minutes (health: starting)                       myoverlay_runner-launcher.pz4prz47duw5ehpz3bj29x9q8.e3ak5gq7e83sat0vc2f8pke9u
```

So the second is "health: starting" instead of (healthy).

Do you have any clues?

Thanks!

**Comment by sxiii** [comment]
I think the problem might be this:
* the "dvv" launched service has it's own IP
* while; swarm-launcher has another IP

What it might mean that when swarm-launcher tries to access localhost on port 3000 it actually can't; because the localhost for swarm-launcher is another "localhost" then the one from "dvv" container. If I am correct, then I should either add static adressing to both containers (I don't know how; tried 10 options already but all of them ain't working) and do a `curl -f http://docker_dvv_ip:3000` or somehow I need run both containers over the same source host; which I don't know how to do. . .

Thank you @tlex for your help anyways!

**Comment by tlex** [comment]
You are correct.

So, there are a few thing here:
* If you create `myoverlay`, there's no need to re-create it in your stack.yml file.
* make your life easier and give the container a name. the healthcheck should use that name instead of `localhost` - the environment variable is `LAUNCH_CONTAINER_NAME`
* if you decide not to name your container, from your output you can see that the container is named `dvvp_DVVS_1` - use that instead of `localhost`

Your `stack.yml` should look like this (**assuming you've created the network already**):
```yml
version: "3.7"

services:
  runner-launcher:
    deploy:
      mode: global
      restart_policy:
        delay: 5s
    image: ixdotai/swarm-launcher:latest
    networks:
      - myoverlay
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
    environment:
      LAUNCH_IMAGE: dvv
      LAUNCH_PROJECT_NAME: 'DVVP'
      LAUNCH_SERVICE_NAME: 'DVVS'
      LAUNCH_PRIVILEGED: 'true'
      LAUNCH_EXT_NETWORKS: 'myoverlay'
      LAUNCH_ENVIRONMENTS: 'access_token=some_token'
      LAUNCH_DEVICES: '/dev/net/tun:/dev/net/tun'
      LAUNCH_VOLUMES: '/var/run/docker.sock:/var/run/docker.sock:rw'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://dvvp_DVVS_1:3000"]
      timeout: 5s
      retries: 15
      start_period: 30s
networks:
  myoverlay:
    external: true
```

**Comment by sxiii** [comment]
:dancer: wow it seems to be working.

What I've done is adding to the environment:
```
      LAUNCH_CONTAINER_NAME: 'viewer'
```
And then quite obviously adding to healthcheck:
```
      test: ["CMD", "curl", "-f", "http://viewer:3000"]
```
Now both containers are happy & healthy! It's so nice! Thanks @tlex you're my hero.

I think I will close the issue now! Thanks again!

**Comment by sxiii** [comment]
P.S. Is there any clear & easy way to launch 2..3..5 containers from the "stack.yml" file, of the "dvv" type instead of 1? I think it has to do something with --global...

**Comment by sxiii** [comment]
Actually; after half an hour here's what's happend:
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                      PORTS               NAMES
dc217a6c1726        dvv                             "/run.sh"                26 minutes ago      Up 26 minutes (unhealthy)                       viewer
a3068f4b607b        ixdotai/swarm-launcher:latest   "/bin/sh -c /entrypo…"   26 minutes ago      Up 26 minutes (healthy)                         myoverlay_runner-launcher.ty6qs1ztty6q389ay2umd3dxm.3cg9c7b8l215ajyf0a8lt35bo
```

Still seems that they are on different networks or anyway the swarm-launcher doesen't see that "viewer" is ill and does not restart it; weirdly.

**Comment by tlex** [comment]
You will probably need to tune the parameters for the healthcheck. Try setting everything lower, especially the retries.

However, it's not swarm-launcher that takes care of the restart, but docker swarm. So, if the healthcheck for swarm-launcher healthy, swarm will not restart it. You'll need to make sure that the `CMD` you've specified actually returns a failure once your container isn't working properly.

**Comment by sxiii** [comment]
Hi @tlex. I've shortened the healthchecks and basically there was 14 working containers. After 6 hours there still was 13 working out there (one might be actual hardware or internet fault or some other complex reasons). So basically it seems to be working fine.

So the last thing I need to understand if I can deploy let's say 2 or 3 containers per each docker swarm node? Do you know how could I add this to my `stack.yml` easily? Thanks!

**Comment by tlex** [comment]
The only way I can think of is to start 2-3 instances of swarm-launcher, each with a separate (different named) sub-container. So, you would have something like:
```yml
services:
  launcher-1:
    [...]
  launcher-2:
    [...]
  launcher-3:
    [...]
```
If you leave "mode: global", this effectively starts 3 launchers for every docker node you have.

Don't forget to set 3 different `LAUNCH_CONTAINER_NAME` and to modify the healthchecks accordingly.

I would also strongly suggest you use different networks, of the type "bridge", not "overlay". If you use "overlay", any container with the same name attached to the same network on another node will answer the healthcheck.

**Comment by sxiii** [comment]
Yeah @tlex that was good idea for the having mutliple definitions of containers and it seems working nicely.

The last thing is: should I create manually each time (I've done as you recommended):
```
sudo docker network create -d bridge --attachable --scope=swarm myoverlay
```
Or can I somehow declare to create the network inside of stack.yml (if I understood correctly)?

Thank you very much for your very extended help out here!

**Comment by tlex** [comment]
Assuming that you've named your stack `foo` (when running `docker stack deploy foo`), you could, in theory, do this:

```yml
networks:
  mynetwork:
    driver: 'bridge'
    attachable: true
```

And then set `LAUNCH_EXT_NETWORKS` to `foo_mynetworks` for all three services.

**Comment by sxiii** [comment]
Hi @tlex ... I was playing whole day today with the containers and I found a really strange thing... Here:
```
s3@s3-phenom:~/work/docker-vpn-viewer$ sudo docker service ls
ID                  NAME                  MODE                REPLICAS            IMAGE                           PORTS
34lsenweczzi        fff_runner-launcher   global              10/15               ixdotai/swarm-launcher:latest  
```
And that's happening all the time. I had 10 of 15 or sometimes like 11 of 16 or 18; but never all of them had replicated.

When I run `sudo docker ps` on some machines; they are not having any processes running even being inside of swarm.

I thought it might have do something with having 4 swarm managers (I had 4 swarm managers and around 20 machines total) so I removed all of the managers; leaving only 1. But it didn't helped.

Also about a small tweak I realized that I don't need to do two health checks -> one from inside of my container and another is from your launcher -> so I removed the health check from inside of the my container. So now only who's looking for the health of my container is your wrapper :) I think this might save a little bit of resources. But...

The problem of not replicated containers is still there. I've checked OS versions (they are similar on most hosts -> it's manjaro of the same version; updated to latest software); then; I've updated docker everywhere to 19.03.6; but still... They don't want to replicate to 100% or even 90% of the nodes.

I really don't know if this might be because of the wrapper or I misconfigured the swarm somehow? Do you know any places to debug? This is my current setup:
```
s3@s3-phenom:~/work/docker-vpn-viewer$ sudo docker node ls
ID                            HOSTNAME                STATUS              AVAILABILITY        MANAGER STATUS      ENGINE VERSION
xrcx...     acer                    Ready               Active                                  19.03.6
vrv4...     aspire-one-522          Ready               Active                                  19.03.6
37jm...     dell                    Ready               Active                                  19.03.6
fmdd...     dell-solus              Ready               Active                                  19.03.5-ce
tz16...     hp                      Ready               Active                                  19.03.6
ib4a...     hp-elite-2540p          Ready               Active                                  19.03.6
epuo...     hp-elite-8440p-lr       Ready               Active                                  19.03.6
rgfn...     hp-elitebook-2540       Down                Active                                  19.03.6
fain...     hp-elitebook-2540p-lr   Ready               Active                                  19.03.6
2l0e...     hp-elitebook-2540p-lr   Down                Active                                  19.03.6
kldg...     hp-elitebook-8440p      Ready               Active                                  19.03.6
s3gr...     hp-ok                   Ready               Active                                  19.03.6
wsum...     localhost.localdomain   Ready               Active                                  19.03.6
wogj...     manjaro                 Ready               Active                                  19.03.6
c8lb... *   s3-phenom               Ready               Active              Leader              19.03.6
wgn5...     s-Lenovo-Z50-75         Down                Active                                  19.03.6
33ko...     s-lenovo                Ready               Active                                  19.03.6
irqt...     sb-sat                  Ready               Active                                  19.03.6
dd1y...     t490s                   Ready               Active                                  19.03.6
```

**Comment by tlex** [comment]
This is already way outside the scope of `swarm-launcher`.

When you deploy a service with `mode: global`, you tell docker swarm to plan one instance of the service on every node. However, considering that you have nodes that are "Down", the service can't be started on them.

I really can't imagine a usecase for that even for a home lab. You're better off looking at [replicas](https://docs.docker.com/compose/compose-file/#replicas) instead of `global`.

**Comment by sxiii** [comment]
@tlex thanks for hints.

So I am having this now:
```
...
      LAUNCH_EXT_NETWORKS: 'myoverlay_myoverlay'
...
networks:
  myoverlay:
    driver: bridge
    attachable: true
```

And when I run this; I got the following:
```
failed to create service myoverlay_runner-launcher: Error response from daemon: The network myoverlay_myoverlay cannot be used with services. Only networks scoped to the swarm can be used, such as those created with the overlay driver.
```
I will try to go back in creating the network manually...

And thanks for the hints about replicas. Actually, in the future I would like to specify which node has to have which amounts of containers: for example, some of them would have only 1, while others 2-3 and little amount of nodes having 4, 5 or 6 containers. I'm totally wasted at this moment in thoughts how that can be achieved (because different hardware performs best with some amount of conainers). Sometimes I think that I better destroy the SWARM totally; and just take multissh (parallel ssh/whatever) and do a CRON script that will go through all hosts and start some specific amount of containers manually on each. Then, 2 times per day it will go again and kill all instances and start a new ones. Or something like that. I don't know if that will be better then swam (probably not); but much less pain in configurations... :DD

**Comment by sxiii** [comment]
And the thing about "nodes being down": I'm having 2-3 nodes down while the service replicates to 9 or 10 nodes out of 15. So; it should be actually replicated to 12-13. That's what stucks me: currently I have 3 laptops (swarm worker hosts) that ARE online; I am running `sudo docker info` and I see them inside of the swarm; but not a single of these 3 laptops even tries to launch anything! I've double-checked the containers (the "dvv" one) and they are absolutely the same as on the hosts where it actually WORKS... So I'm really stucked why they are not doing anything

**Comment by sxiii** [comment]
LOL.
```
s3@s3-phenom:~/work/docker-vpn-viewer$ sudo docker node ls | wc -l
22
s3@s3-phenom:~/work/docker-vpn-viewer$ sudo docker service ls
ID                  NAME                        MODE                REPLICAS            IMAGE                           PORTS
5q9bccmqj406        myoverlay_runner-launcher   global              12/15               ixdotai/swarm-launcher:latest  
```
So, I've got total of 22 nodes; of which `sudo docker node ls` shows 6 down; but still the docker stack tries to replicate only to 15 (should be 16; because 16+6=22)...

So this is still _WEIRD_!

**Comment by sxiii** [comment]
Hi @tlex =) After fiddling with container second day; multiple-times recreating my swarm; I've finally managed to run in mostly everywhere (except two laptops that are working from SD card; weirdly).

I think I will let the task run for one day without any touches to see if it performs well; and then continue with adding second parallel container.

But the question about auto-creating network (the previous one) still stays on... Thanks anyway

**Comment by tlex** [comment]
I've just added documentation about networking: https://github.com/ix-ai/swarm-launcher/wiki/networking

Please take a look and see if it helps

**Comment by sxiii** [comment]
Wow this is super nice @tlex I think it answered all my questions about networking. I'll relook at my stack.yml file if it's fine or not.

I've continued my research on running 2 containers on each host with 2 swarm launchers. In general; they seems to work fine; but some fun stuff happens sometimes:
* The laptops which are older and has not powerful enough hardware (probably) are dropping out at least one out of two containers; and sometimes both containers tries to restart (even when I made a different restarting times; delays etc.)
* After they work for some time; they got "locked" in a healthy state (usually after 2 to 8 hours) and they seems to be "healthy" according to the data from swarm; altho I see from external services they they are fully dead and not communicating anymore.

I bet this probably has nothing to do with swarm-launcher and it's either a chromium (I run chromium inside yes) issue or an issue of docker swarm itself.

But I will still update the thread if I manage to run two containers constantly without any significant errors so somebody might find it helpful maybe.

I think you can also copy your main readme page to wiki because it's also very explanatory. So people could have everything in one place. And then link the wiki from readme :=)

Thank you for all your work.

Den

**Comment by sxiii** [comment]
@tlex sorry for disturbing again... But I still have network issues and I can't fix it after few days of trying already.

I think I need to tell you more details on the whole setup.

Inside of the container there is a chromium-like browser. Each container connects to a VPN by using OpenVPN client. I don't want for any of the chromium-containers to be in the same network; ever.

What I need is that the swarm-launcher itself would be in the same network with the chromium. So if it launches chromium, it should be on the same network; to perform the health checks.

What I am currently having is I tried with different network options and all the time my containers got killed and restarted by swarm (probably they are restarted with a frequency that I've set up as a delay). So I bet this is because docker-swarm never receives ping-back from the main chromium container.

As I understood while reading your wiki; I do need only the "LAUNCH_NETWORKS" (because I need to have a network of swarm-launcher+chromium on each node) and nothing else.

So, my current setup has this:
```
networks:
  super:
    driver: bridge
    attachable: true
    external: true
services:
  runner-launcher:
    deploy:
      mode: global
      restart_policy:
        delay: 5s
    image: ixdotai/swarm-launcher:latest
    networks:
      - super
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
    environment:
      LAUNCH_NETWORKS: 'super'
     ... (other env variables)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://viewer:3000"]
      interval: 1m
      timeout: 5s
```

As I run this on my swarm; I see constant restarts of the containers.

Can you please elaborate if you see any errors in this config? I really don't want to remove the healthcheck, but restarting the whole thing each minute is too much; just as bad as never restarting at all. I am really stucked.

Sorry for bothering and thank you.

Den

**Comment by tlex** [comment]
It really helps to look at the logs of the runner-launcher container. What stands out is the usage of the `LAUNCH_NETWORKS` variable. From the docs: `Space separated list of project networks to create.` This means, they are created in the scope of the sub-container (the one with chromium) - it means that the `super` network created in the stack file is **not** used.

What you need is to use `LAUNCH_EXT_NETWORKS` with the value `STACKNAME_super` (replace the `STACKNAME` with the name used in the command `docker stack deploy`).

By using `driver: bridge` you ensure that the same network different nodes doesn't see the other nodes (as opposed do `driver: overlay`).

If you want to start multiple `swarm-launcher` containers and you don't want to share the network, define a network for every instance (e.g. `super1`, `super2` .. `superN`).

**Comment by sxiii** [comment]
Hmmm. Okay; but when I:

```
networks:
  super:
    driver: bridge
    attachable: true
...
    environment:
      LAUNCH_PROJECT_NAME: 'DVVP'
      LAUNCH_SERVICE_NAME: 'DVVS'
      LAUNCH_PRIVILEGED: 'true'
      LAUNCH_EXT_NETWORKS: 'super_super'
```

And then, `sudo docker stack deploy --compose-file stack.yml --prune --with-registry-auth super`; it always says: 
```
failed to create service super_runner-launcher: Error response from daemon: network super_super not found
```

**Comment by tlex** [comment]
The name `super_super` should only be used outside the swarm scope, so with `LAUNCH_EXT_NETWORKS`. The error message makes me think you've set it also with the `networks:` key in the launcher service definition.

To recap:
* `LAUNCH_EXT_NETWORKS: super_super`
* `networks:` always without the prefix (both globally and in the service definition)

This assumes that you use `docker stack deploy super`

**Comment by sxiii** [comment]
All containers were totally silent and nothing happened; until I created the network manually:
```
sudo docker network create -d bridge --attachable --scope=swarm super_super
```

Then they began to start. But it's still the same problem: after 3 minutes; the swarmlauncher becomes unhealthy:
```
24dbe07f2419        ixdotai/swarm-launcher:latest   "/bin/sh -c /entrypo…"   3 minutes ago       Up 3 minutes (unhealthy)                       super_runner-launcher.c8lbyraugctpn52mp39vszz58.aj12neljext3ptrrmjtm09cvt
```
And so both containers die. And this repeats constantly on all ~20 nodes. On some it dies even faster in less then one minute.

**Comment by sxiii** [comment]
Yep, in the "network" section and in the services -> networks section the name is just "super". The super_super name I used only ion LAUNCH_EXT_NETWORKS and only there. Still; this approach requires manual network creation and even with that containers are dying constantly @tlex . Can you tell me where I can see the logs?

The thing is that; when I am manually running the same container on a host with the flags I need (--cap-add=NET_ADMIN & --device=/dev/net/tun:/dev/net/tun) the container starts and works flowlessly for hours (I do see it in my admin panel)...

**Comment by sxiii** [comment]
Screenshot from a single node:
![Screenshot_2020-02-23_15-53-25](https://user-images.githubusercontent.com/575925/75114242-dc362900-5654-11ea-98eb-505f2b5ede95.png)

**Comment by tlex** [comment]
This is very strange, since I am using healthchecks (as documented in README) without any problems:
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                 PORTS               NAMES
b4ca76b5686a        gitlab/gitlab-runner:alpine     "/usr/bin/dumb-init …"   4 hours ago         Up 4 hours                                 gitlab-ci-runner
7712529a1e15        ixdotai/swarm-launcher:latest   "/bin/sh -c /entrypo…"   4 hours ago         Up 4 hours (healthy)                       runners_runner-launcher.wgay0ielark3a2wgnthkvy7fc.d5xfpc18ipg9aq01gbm66w9hq
```
I am however using it with driver `overlay` rather than bridge - i suspect `bridge` only creates the network on one node, not on all.

**Comment by tlex** [comment]
The logs you can get with `docker service logs super_runner-launcher`

**Comment by sxiii** [comment]
But is that an issue if I am creating network manually with

```
sudo docker network create -d bridge --attachable --scope=swarm super_super
```
?

**Comment by tlex** [comment]
Take a look at: https://docs.docker.com/engine/reference/commandline/network_create/#bridge-driver-options

You might need to specify `--icc` (but never used it, don't know if it works like this or you need to `--icc=true`)

**Comment by sxiii** [comment]
> Take a look at: https://docs.docker.com/engine/reference/commandline/network_create/#bridge-driver-options
> 
> You might need to specify `--icc` (but never used it, don't know if it works like this or you need to `--icc=true`)

```
s3@s3-phenom:~/work/docker-vpn-viewer$ sudo docker network create -d bridge --attachable --icc --scope=swarm super_super
unknown flag: --icc
See 'docker network create --help'.
s3@s3-phenom:~/work/docker-vpn-viewer$ sudo docker network create -d bridge --attachable --icc=true --scope=swarm super_super
unknown flag: --icc
```

**Comment by tlex** [comment]
`--opt com.docker.network.bridge.enable_icc=true` (but as far as i can see, it should be on by default).

Anyhow, if push comes to shove, as a workaround, you can always create dedicated networks for every host, that you simply don't use on other hosts (by using [placement](https://docs.docker.com/compose/compose-file/#placement)).

It's not really a beautiful solution, but ...

**Comment by sxiii** [comment]
Do you mean to manually create a network on each host by issuing a `docker network create` with unique names everywhere? Or?

I am also thinking maybe I should try pull-back the healthcheck that was built-in inside of the container:
```
HEALTHCHECK --interval=1m --timeout=3s CMD curl -f http://localhost:3000 || exit 1
```
and try to remove the swarm-launcher healthcheck; so in this case the containers does not have to communicate via the network at all. But as I remember last time my healthcheck didn't worked because the container is not launched by a docker swarm rather then a swarm-launcher...

Ahhh.

Sorry for this. I'm just seems like really wasted. 

This is the image that I'm trying to run over the course of the last week... The guys at feelingsurf actually blocked me once already because I am disconnecting too fast from the service (because the containers are obviously restarting all the time :D)...

https://github.com/sxiii/docker-viewer

Maybe if you have time anywhere in the future, you could try (just change the access_token to yours of course so you see results in the panel...

Thanks anyway

Den

**Comment by tlex** [comment]
Considering the commit message for this, i suspect that the problems you're having come from the broken healthcheck: https://github.com/feelingsurf/docker-viewer/commit/1ec4a4308ed3e78a63c75cac02e8377da7d46bf4

I strongly suggest you give it a try with a different container and see if it works. Take https://hub.docker.com/r/browserless/chrome/ for example

**Comment by sxiii** [comment]
@tlex healthcheck inside of the Dockerfile was commented out by me when I started to fiddle with your solution. So it's not the root of the problem.

Also, I need the exact software from these guys (feelingsurf); so even if the browserless/chrome will work fine it won't solve the situation...

But I'll try.

**Comment by sxiii** [comment]
Hi again @tlex :)

I'm still fighting with the healthchecks. Seems docker is updated to 19.03.7. I still have problems with swarm launcher.

* In my config where something at least works; the HEALTHCHECK is enabled only on swarm-laucnehr level; and what happens it just let the main container work for 8-9 minutes then the swarm-launcher becomes unhealthy and restart himself and his child. Seems like an auto-kill-switch feature; but I don't want that when container is healthy. In this case also; the "healthy" state of swarm-laucnher is NEVER reached; it's always "starting..." and after 8-9 minutes -> restart.
* When I enable healthchecks both in the swarm-launcher and my container; usually nothing works.
* I still didn't manage to understand and do an exact network configuration. For the first option when at least something works I use
```
networks:
  super:
    driver: overlay
    attachable: true
    external: true
```
... I'm kinda stucked. Really thinking parrallel SSH and running containers manually on all hosts might do the trick; but I will need to change and update more then 35 credentials (as I have around 35 hosts in this installation)...
